In [1]:
import numpy as np

In [2]:
coord = [(0, 2404, 2120, 0), (0, 2558, 2066, 0), (0, 2070, 1846, 0), (0, 1710, 1782, 0), (0, 2636, 1848, 0), (0, 2334, 1750, 0), (0, 2188, 1752, 0), (0, 1866, 1740, 0), (0, 2760, 1730, 0), (0, 2186, 1708, 0), (0, 2620, 1688, 0), (0, 2486, 1666, 0), (0, 1290, 1764, 0), (0, 2516, 1644, 0), (0, 1526, 1526, 0), (0, 1554, 1438, 0), (0, 1876, 1388, 0), (0, 434, 1216, 0), (0, 958, 1156, 0), (0, 2094, 1020, 0), (0, 514, 974, 0), (0, 1458, 710, 0), (0, 1196, 724, 0), (0, 486, 686, 0), (0, 2212, 764, 0), (0, 1694, 676, 0), (0, 1434, 398, 0)]

In [12]:
len(coord)

27

In [17]:
import math

def distance(point1, point2):
    """
    计算两个点之间的欧式距离
    """
    return math.sqrt((point1[1] - point2[1])**2 + (point1[2] - point2[2])**2 + (point1[3] - point2[3])**2)

def merge_coordinates(coordinates, threshold):
    """
    合并距离小于阈值的坐标
    """
    merged_coordinates = []
    merged_indices = set()

    for i in range(len(coordinates)):
        if i not in merged_indices:
            # 将当前坐标加入到合并坐标中
            merged_indices.add(i)
            merged_point = list(coordinates[i])
            count = 1

            # 寻找距离小于阈值的其他坐标并合并
            for j in range(i+1, len(coordinates)):
                if j not in merged_indices:
                    if distance(coordinates[i], coordinates[j]) < threshold:
                        merged_point[1] += coordinates[j][1]
                        merged_point[2] += coordinates[j][2]
                        count += 1
                        merged_indices.add(j)

            # 计算中点坐标
            merged_point[1] /= count
            merged_point[2] /= count

            merged_coordinates.append(tuple(merged_point))

    return merged_coordinates

# 示例坐标列表
coordinates = [(1, 1, 2, 3), (2, 4, 5, 6), (3, 7, 8, 9), (4, 3, 4, 5), (5, 1, 2, 3)]

# 设置阈值
threshold = 100
coord = []
# 合并坐标
merged = merge_coordinates(coord, threshold)

# 打印合并后的坐标
print("合并后的坐标：", len(merged))


合并后的坐标： 0


In [11]:
len(merge_coordinates(coord, 200))

19

In [3]:
import numpy as np

In [18]:
a = np.array([[1, 2, 34], [22, 111, 555]])

In [19]:
a

array([[  1,   2,  34],
       [ 22, 111, 555]])

In [20]:
a = a[::-1, ::-1]

In [21]:
a

array([[555, 111,  22],
       [ 34,   2,   1]])

In [14]:
a[0:2, :] = 0

In [15]:
a

array([[0, 0, 0],
       [0, 0, 0]])

In [16]:
a[-3:1, :] = 1 

In [17]:
a

array([[1, 1, 1],
       [0, 0, 0]])

In [22]:
print(a[:, 3:5].shape)

(2, 0)


In [23]:
a

array([[555, 111,  22],
       [ 34,   2,   1]])

In [24]:
b = np.array([[0, 0, 1], [1, 0, 0]])

In [28]:
a = np.logical_or(a, b)

In [29]:
a

array([[ True,  True,  True],
       [ True,  True,  True]])